# Generated by Django 5.1.7 on 2025-03-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="invoice_file",
        ),
    ]
