# Generated by Django 5.1.7 on 2025-03-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_invoice_invoice_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_file",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
    ]
