# Generated by Django 5.1.7 on 2025-03-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_invoice_invoice_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateTimeField(),
        ),
    ]
