# Generated by Django 5.1.7 on 2025-03-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_invoice_invoice_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(),
        ),
    ]
