# Generated by Django 5.1.7 on 2025-03-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_invoice_invoice_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("Processing", "Processing"),
                    ("Review", "Review"),
                    ("Pending for Approval", "Pending for Approval"),
                    ("approved", "Approved"),
                    ("Paid", "Paid"),
                    ("Closed", "Closed"),
                ],
                default="Processing",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=255),
        ),
    ]
