# Generated by Django 5.1.7 on 2025-03-27 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_invoice_status_alter_invoice_invoice_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendor",
            old_name="name",
            new_name="invoice_number",
        ),
        migrations.AddField(
            model_name="vendor",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="vendor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="invoice_file",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[
                    ("Processing", "Processing"),
                    ("Review", "Review"),
                    ("Pending for Approval", "Pending for Approval"),
                    ("approved", "Approved"),
                    ("Paid", "Paid"),
                    ("Closed", "Closed"),
                ],
                default="Processing",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="vendor_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
