# Generated by Django 5.1.7 on 2025-03-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_vendor_account_number_vendor_address_line1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="status",
            field=models.CharField(default="Processing", max_length=50),
        ),
    ]
