# Generated by Django 5.1.7 on 2025-04-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_vendor_amount_alter_vendor_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="is_validated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("vendor", "invoice_number")},
        ),
    ]
